const quotes = [
    "This sentence is false!!",
    "Time is relative, not " + new Date().toLocaleTimeString([], {hour: 'numeric', minute: 'numeric', hour12: true}),
    "A Minecraft Movie sucks.",
    "It's opposite day!",
    "Get good!",
    "I'm too lazy to write anything good.",
    "What about you?",
    "Too much of a good thing is not bad.",
    "instance2d.js.org",
    "Go watch youtube.",
    "Theres a good chance i'm not online right now.",
    "This is ai generated.",
    "As an AI language model developed by OpenAI, I don't have consciousness, personal experiences, or opinions. My responses are generated based on patterns in data and designed to assist with information and tasks.",
    "A “Hello, world!” program is traditionally used to introduce novice programmers to a programming language. “Hello, world!” is also traditionally used in a sanity test to make sure that a computer language is correctly installed, and that the operator understands how to use it.",
    "Give me money.",
    "As an AI language model, I don't have a body, senses, or physical presence—so I can't see, hear, touch, or interact with the world like a human can.",
    "I should walk more.",
    "Do you have any grass?",
    "Give me money.",
    "I always come back.",
    "I AM STEVE",
    "Go touch some grass.js",
    "Go touch some grass.jpeg",
    "Why do fake backgrounds on images even exist.",
    "Why did the chicken cross the road? Because he was going home.",
    "Im gonna touch you lil bro",
    "I dont get why more people dont download ram.",
    "The cake is a lie.",
    "GLADOS",
    "These quotes were automatically generated by A.R.G (Automatically Reconstructed Greetings). Please give feedback <a target='_' class='no-underline blue-text underline-on-hover' href='/arg-feedback'>here</a>."
]

const quote = document.getElementById("quote")

function change() {
    const number = Math.ceil(Math.random() * quotes.length)
    const text = quotes[number - 1]
    console.log(text)
    quote.innerHTML = text
}

change()

setInterval(change, 1000)